### ISSUE TITLE
Create workflow for FPCC to update data

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/trailsy#171]

**Comment by shua123** [comment]
- [ ] Bulk csv replace is up on staging.
- [ ] Allow admin to update individual records through site.

**Comment by versatilehuman** [comment]
For trails.csv it's warning that **geom** is an extra column:

![image](https://user-images.githubusercontent.com/7032169/56043849-ad94b580-5d03-11e9-90ca-c2d774110e5a.png)

**Comment by versatilehuman** [comment]
It is staging the new trails.csv, but not updating:

![image](https://user-images.githubusercontent.com/7032169/56044456-d49fb700-5d04-11e9-9624-dea145b835a0.png)

**Comment by versatilehuman** [comment]
@shua123 Were you able to get trail uploads working?

**Comment by shua123** [comment]
@versatilehuman  yes. It should be working.

**Comment by versatilehuman** [comment]
@shua123 I was able to get through a trails.csv update.

trails_desc.csv - After I hit "create update" I get a blank page.

**Comment by shua123** [comment]
@versatilehuman The short answer is that there is a character encoding issue with some of the characters in one of the descriptions. Can you send me the version the csv you were testing?

**Comment by versatilehuman** [comment]
Current data and I added the missing River Trail hours2
https://github.com/fpdcc/webmap_data_updates/blob/master/map%20data/trails_desc.csv

**Comment by shua123** [comment]
@versatilehuman Please send me the exact file after your modification.

**Comment by versatilehuman** [comment]
@shua123 Sent to your gmail.

**Comment by shua123** [comment]
@versatilehuman Okay, the version on staging now won't fail but you'll have to notice the bad character encoding translations. 

Its not liking an apostrophe and emdash in the Sagawau Environmental Learning Center description. Try to fix those and re-upload. Ideally the csv and content should all be utf-8.

https://map-staging.fpdcc.net/updates/67

**Comment by versatilehuman** [comment]
This looks good.

**Comment by versatilehuman** [comment]
@shua123 Minor: If I don't check the "perform this update" checkbox, and hit "update" I still get a success message (Update was successfully updated), even though when I check back to the update list it failed.

**Comment by versatilehuman** [comment]
@shua123 Please shoot me an email to my .gov whenever everything is up on production.
