### ISSUE TITLE
Evaluate Tangram + vector tile basemap

### ISSUE THREAD

**Issue by shua123** [fpdcc/trailsy#200]
Evaluate using Tangram with vector tiles for new basemap.

Dev version at https://smartchicago.github.io/trailsy/

Needed customization:
- This currently needs a manual build of the Tangram js master branch since it contains a bug fix that hasn't made it to a released version yet.
- This version modifies the leaflet.zoomcss.js plug in to round zoom levels to the nearest whole number since Tangram zooming does partial zoom levels. https://github.com/smartchicago/trailsy/blob/cc-imagery/js/vendor/leaflet.zoomcss.js#L30

Issues:
1. Tile loading seems slow. I think this is because of the nextzen server it is pulling from right now.
2. Its still sometimes not re-positioning items on zoom/movement.

**Comment by versatilehuman** [comment]
@shua123 Didn't find anything new testing it. 

Check out the notes under "Internal" at the end of this release and see if any of those adjustments re: Leaflet are relevant:
https://github.com/tangrams/tangram/releases/tag/v0.14.0

**Comment by shua123** [comment]
I found an undocumented Tangram option that I think has fixed our main zoom icon out of place issues. (https://github.com/smartchicago/trailsy/blob/gh-pages/js/map.js#L163)

Try it out now @versatilehuman

**Comment by shua123** [comment]
We moved this to production. Performance still isn't ideal so this may evolve into a new solution.

**Comment by versatilehuman** [comment]
Time to revisit.

**Comment by versatilehuman** [comment]
Moved to https://github.com/fpdcc/trailsy/issues/278

**Comment by ccjoshk** [comment]
Closing because we are moving away from Tangram towards using an ESRI vector tile basemap with esri-leaflet

**Comment by gisdevcc** [comment]
Closing because we are moving to ESRI vector tile basemaps with esri-leaflet
