### ISSUE TITLE
Add "no dogs" icon & data

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/trailsy#213]
For nature centers and illinois nature preserves.

**Comment by shua123** [comment]
No dogs icons & panel info added to map https://github.com/fpdcc/trailsy/commit/e91d6d80193e67b1635905bcee23ec745639cedd. Data and server code still needs to be added.

**Comment by shua123** [comment]
on staging

**Comment by versatilehuman** [comment]
I'm seeing no_dogs in the latest points_of_interest data but not showing up on staging.

Example:
https://map-staging.fpdcc.net/#/?poi=15-Green+Lake+Family+Aquatic+Center

**Comment by versatilehuman** [comment]
Looks good.
