### ISSUE TITLE
Consider assigning activities by trail segment

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/trailsy#214]
Since these are automatically assigned based on surface, we will have an issue once we implement activity icon display on pop-ups (#107).

Example: 

Oak Forest Heritage Trails. This isn't an issue now because the panel only displays 1+ mile trails. But after the pop-up icons are added, this will imply horses are allowed on the unpaved trails:

![image](https://user-images.githubusercontent.com/7032169/47246020-4d126480-d3c1-11e8-9a07-ceac110e6bd2.png)

**Comment by versatilehuman** [comment]
We are moving forward with this:
https://github.com/fpdcc/webmap_data_updates/issues/118

@shua123 Any thoughts?

**Comment by shua123** [comment]
@versatilehuman Please address https://github.com/fpdcc/webmap_data_updates/issues/118#issuecomment-481733780 here

**Comment by versatilehuman** [comment]
Both panel and popup should:

- Show icon if more 1s than 0s
- Not show icon if more 0s than 1s
