### ISSUE TITLE
Add Nature Center Trails

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/trailsy#216]
Moving forward on this:
https://github.com/fpdcc/webmap_data_updates/issues/119

Then we will tweak naming to first check for an actual name. If they don't have a name, would fall back to:

> trail_type + trail_color + segment_type (direction)

@shua123 Thoughts?

**Comment by shua123** [comment]
on staging

**Comment by versatilehuman** [comment]
Behavior looks good. Some issues @glw needs to address on https://github.com/fpdcc/webmap_data_updates/issues/164
