### ISSUE TITLE
Bicycling search

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/trailsy#221]
A search for "bicycling":
![image](https://user-images.githubusercontent.com/7032169/50096885-4c8a2480-01de-11e9-8269-3c42f01f8faa.png)

Should trigger the "biking" search:
![image](https://user-images.githubusercontent.com/7032169/50096844-3d0adb80-01de-11e9-9681-800c82282cd2.png)

**Comment by shua123** [comment]
Deployed on staging

**Comment by shua123** [comment]
Deployed in production https://github.com/fpdcc/trailsyserver/commit/f38f2173fddbdcdbd366ba08d14478018497696f#diff-98950be441256595938575eb0915b103
