### ISSUE TITLE
Update Hiking Label

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/trailsy#224]
Based on some messaging research we've been compiling, we want to make sure to include "walk" in the label, this change will also match the new website.

We can bundle this in to other updates we'll need to make re: nature center trails and trail IDs.

Change this:
![image](https://user-images.githubusercontent.com/7032169/55360362-c4344480-5499-11e9-8f53-434af30445f6.png)

to this:

![image](https://user-images.githubusercontent.com/7032169/55360393-dc0bc880-5499-11e9-89b2-e0bf69c07455.png)

**Comment by shua123** [comment]
Live on staging 00833bccdb920c709fb6e25bf80735701ef20245

**Comment by versatilehuman** [comment]
Looks good.
