### ISSUE TITLE
Update No Alcohol label

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/trailsy#225]
We are changing our Alcohol policy and expanding sites that are considered "no alcohol"

Change this:
![image](https://user-images.githubusercontent.com/7032169/55428024-eab3b780-554d-11e9-9e99-b35ec3504e24.png)

to this:
![image](https://user-images.githubusercontent.com/7032169/55428099-07e88600-554e-11e9-8cc6-ab2d99512328.png)

**Comment by shua123** [comment]
Live on staging 00833bccdb920c709fb6e25bf80735701ef20245
