### ISSUE TITLE
fitness_stairs addition

### ISSUE THREAD

**Issue by shua123** [fpdcc/trailsy#226]
It looks like fitness_stairs has been added to the poi data https://github.com/fpdcc/webmap_data_updates/issues/145. I do not know what corresponding changes need to be made to the trailsy map.

**Comment by versatilehuman** [comment]
Add this after No Dogs
https://github.com/fpdcc/trailsy/blob/development/js/panelFunctions.js#L643
```
// fitness_stairs = Fitness Stairs
        if (poi.properties.tags[':panel'].indexOf('fitness_stairs') > -1) {
          fpccAmenitiesString += "<div class='fpccAmenity'><svg class='icon icon-stairs'><use xlink:href='icons/defs.svg#icon-stairs'></use></svg><span class='fpccAmenityTitle'>Fitness Stairs</span></div>"
        }

// zip_line = Zip Line
        if (poi.properties.tags[':panel'].indexOf('zip_line') > -1) {
          fpccAmenitiesString += "<div class='fpccAmenity'><svg class='icon icon-zip-line'><use xlink:href='icons/defs.svg#icon-zip-line'></use></svg><span class='fpccAmenityTitle'>Zip Line / Treetop Adventure</span></div>"
        }

```
Add these into existing rule-sets for those fills (https://github.com/fpdcc/trailsy/blob/development/styles/css/newguts.css#L370)

```
#icon-stairs .path1,#icon-zip-line .path1{fill:#585747}
#icon-stairs .path2,#icon-zip-line .path2,#icon-zip-line .path3,#icon-zip-line .path4{fill:#fff}
```
Remove this:
https://github.com/fpdcc/trailsy/blob/development/js/panelFunctions.js#L509

```
// recreation_center = Special Acitivty
        if (poi.properties.tags[':panel'].indexOf('recreation_center') > -1) {
          fpccAmenitiesString += "<div class='fpccAmenity'><svg class='icon icon-rec-center'><use xlink:href='icons/defs.svg#icon-rec-center'></use></svg><span class='fpccAmenityTitle'>Special Activity</span></div>"
        }
```

**Comment by versatilehuman** [comment]
## Activity Icons on Map Changes

https://github.com/fpdcc/trailsy/blob/development/js/activityFeature.js#L115

Remove:
`: activityType === 'recreation center' ? 'icon-rec-center'`

Add:
`: activityType === 'fitness stairs' ? 'icon-stairs'`

Update:
"zip line" needs to be two words
`: activityType === 'zip line' ? 'icon-zip-line'`

**Comment by shua123** [comment]
on staging

**Comment by versatilehuman** [comment]
Looks good.
