### ISSUE TITLE
Schema changes for 4/9 data

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/trailsy#227]
@glw Can you confirm?

## trails
Added:
- [ ] hiking
- [ ] biking
- [ ] cross_country
- [ ] equestrian
- [ ] no_dogs _(will be included on 4/10 update)_
- [ ] dogs_leash _(will be included on 4/10 update)_
- [ ] trail_subsystem_id
- [ ] trail_name

## trails_desc
Added:
- [ ] hours1	
- [ ] hours2	
- [ ] season1	
- [ ] season2	
- [ ] special_hours

## points_of_interest
Added:
- [ ] fitness_stairs

Removed:
- [ ] recreation_center

**Comment by glw** [comment]
All done!

> @glw Can you confirm?
> 
> ## trails
> Added:
> 
> * [x]  hiking
> * [x]  biking
> * [x]  cross_country
> * [x]  equestrian
> * [x]  no_dogs _(will be included on 4/10 update)_
> * [x]  dogs_leash _(will be included on 4/10 update)_
> * [x]  trail_subsystem_id
> * [x]  trail_name
> 
> ## trails_desc
> Added:
> 
> * [x]  hours1
> * [x]  hours2
> * [x]  season1
> * [x]  season2
> * [x]  special_hours
> 
> ## points_of_interest
> Added:
> 
> * [x]  fitness_stairs
> 
> Removed:
> 
> * [ ]  recreation_center

**Comment by shua123** [comment]
all on staging
