### ISSUE TITLE
Update Trail Panel for new schema

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/trailsy#228]
## icons

Update these functions to reflect new schema:
- hiking
- biking
- cross_country
- equestrian
- no_dogs (will be included on 4/10 update)
- dogs_leash (will be included on 4/10 update)

https://github.com/fpdcc/trailsy/blob/development/js/panelFunctions.js#L996

In this order:
```
<svg class="icon icon-hiking"><use xlink:href="icons/defs.svg#icon-hiking"></use></svg>
<svg class="icon icon-bicycling"><use xlink:href="icons/defs.svg#icon-bicycling"></use></svg>
<svg class="icon icon-dog-leash"><use xlink:href="icons/defs.svg#icon-dog-leash"></use></svg>
<svg class="icon icon-cross-country-skiing"><use xlink:href="icons/defs.svg#icon-cross-country-skiing"></use></svg>
<svg class="icon icon-equestrian"><use xlink:href="icons/defs.svg#icon-equestrian"></use></svg>
<svg class="icon icon-no-dogs"><use xlink:href="icons/defs.svg#icon-no-dogs"></use></svg>
```

## hours

Replicate the poi hours functionality, but for trails: 
https://github.com/fpdcc/trailsy/blob/development/js/panelFunctions.js#L785

Pulling from new columns in **trails_desc**:
- hours1
- hours2
- season1
- season2
- special_hours

**Comment by shua123** [comment]
on staging

**Comment by versatilehuman** [comment]
It looks like the season2/hours2 block is missing from the trails hours:

![Screen Shot 2019-04-14 at 10 54 26 AM](https://user-images.githubusercontent.com/7032169/56095546-b4f2c500-5ea3-11e9-943c-13cfe966d9f5.png)



## Styling
In newguts.css add this after line 151 https://github.com/fpdcc/trailsy/blob/development/styles/css/newguts.css#L151

`.fpccTrails .fpccHours{margin:0}`

**Comment by shua123** [comment]
The missing hours2 for River Trail Nature Center Trails is a data issue. https://github.com/fpdcc/webmap_data_updates/blob/master/map%20data/trails_desc.csv#L31

See https://map-staging.fpdcc.net/#/?trail=Crabtree+Nature+Center+Trails for a working hours2.

**Comment by versatilehuman** [comment]
Sorry, I glanced at trails_desc and it looked like they were all in there. Definitely that single one missing.
