### ISSUE TITLE
Trail segment popup length & icons

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/trailsy#229]
Breaking this out and updating from #107 

In trailSegmentFeature.js, here-ish:
https://github.com/fpdcc/trailsy/blob/development/js/trailSegmentFeature.js#L126

Under Trail segment name div (`<div class="trail-popup-line trail-popup-line-named trail-segment"`... `</div>`) add:

```
<div class="trail-popup-line trail-popup-line-named fpccPopupData">
<div class="fpccPopupDataCont clearfix">
<div class="fpccPopupLength">[segment length here]</div> 
<div class="fpccPopupIcons">[activity icons here, include new dog_leash/no_dogs]</div>
</div>
</div>
```

add after line 340 in newguts.css:
https://github.com/fpdcc/trailsy/blob/development/styles/css/newguts.css#L340
```
.trail-popup .trail-popup-line.fpccPopupData{padding-top:0}
.fpccPopupData .fpccPopupDataCont{text-transform: none;border-top:1px dotted #CCC;padding:.65em 0 .5em;margin: 0;}
.fpccPopupData .fpccPopupLength{margin-bottom: .65em}
.fpccPopupData .fpccPopupIcons .icon{width: 16.5em;height: 1.65em;margin-right: .25em}
```

**Comment by shua123** [comment]
On staging. This looks a little weird right now. Probably needs some tweaks.

**Comment by versatilehuman** [comment]
On the pop-ups, Let's do:

Length: X.XX mi


Update:
https://github.com/fpdcc/trailsy/blob/development/styles/css/newguts.css#L339
to:
`.trail-popup .trail-popup-line-named,.picnicgrove-capacity{border-top:none;padding:.5em .75em;width:100%}`

https://github.com/fpdcc/trailsy/blob/development/styles/css/newguts.css#L340
to:
`.trail-popup .trail-popup-line-named.trail-segment,.picnicgrove-capacity{border-top:2px solid #e3e3e1;width:100%}`

**Comment by versatilehuman** [comment]
Looks good.

**Comment by versatilehuman** [comment]
@shua123 One more tweak:

Add max-width to end of this https://github.com/fpdcc/trailsy/blob/development/styles/css/newguts.css#L324

`.leaflet-popup-content-wrapper .leaflet-popup-content{font-family:Helvetica,Arial,sans-serif;border-bottom:2px solid #606D29;color:#333;min-width:10em;width:auto;height:auto;margin:0;position:relative;background-color:#fff;font-size:13px;line-height:1.5;text-transform:capitalize;max-width:225px}`

**Comment by shua123** [comment]
@versatilehuman done and on staging

**Comment by versatilehuman** [comment]
Looks good.
