### ISSUE TITLE
Remove Smart Chicago link

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/trailsy#230]
Keep the mention of Smart Chicago, just remove the link. Domain is no longer active and I can't find a mention of Smart Chicago or the project on the CityTech website:
![image](https://user-images.githubusercontent.com/7032169/55992532-6ad6cd00-5c72-11e9-81dc-7efbbe218422.png)

**Comment by shua123** [comment]
on staging

**Comment by versatilehuman** [comment]
Looks good.
