### ISSUE TITLE
Non-FPCC coloring and labels

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/trailsy#231]
It looks like the coloring and labeling (Non Fpcc vs. Non-FPCC) got messed up. Not sure if this is data related.

Staging:
![Screen Shot 2019-04-14 at 10 25 50 AM](https://user-images.githubusercontent.com/7032169/56095200-eec1cc80-5e9f-11e9-90b6-30e11c5494b6.png)

Production:
![Screen Shot 2019-04-14 at 10 27 57 AM](https://user-images.githubusercontent.com/7032169/56095213-0436f680-5ea0-11e9-81f9-a79769f78597.png)

**Comment by shua123** [comment]
That's me I think.

**Comment by shua123** [comment]
Yes this is me

**Comment by versatilehuman** [comment]
Looks good.
