### ISSUE TITLE
Alert json missing link field

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/trailsy#235]
So the link is on the map, but doesn't make it to the website:

![image](https://user-images.githubusercontent.com/7032169/56318585-1ecdd180-6125-11e9-946c-df8b1eb7cb3c.png)

![image](https://user-images.githubusercontent.com/7032169/56318680-4b81e900-6125-11e9-8deb-fa3ed6a16f85.png)

![image](https://user-images.githubusercontent.com/7032169/56318706-53418d80-6125-11e9-96e6-e21633a13cb1.png)

**Comment by versatilehuman** [comment]
@shua123 Can this be included within the description of the JSON file or do we need to add a separate entry? See related: #220 

Included:
`{"id":"337","name":"Allison Woods","map_id":"337-Allison Woods","web_link":"https://fpdcc.com/places/locations/allison-woods/","type":"poi","alerts":[{"id":3196,"alert_type":"closure","origin_type":"Pointsofinterest","start_date":"12/02/2019","end_date":"03/31/2020","description":"Closed for land management. <a href="https://fpdcc.com/about/plans-projects/">More information ></a>"}]}`

New entry:
`{"id":"337","name":"Allison Woods","map_id":"337-Allison Woods","web_link":"https://fpdcc.com/places/locations/allison-woods/","type":"poi","more_information":"https://fpdcc.com/about/plans-projects/","alerts":[{"id":3196,"alert_type":"closure","origin_type":"Pointsofinterest","start_date":"12/02/2019","end_date":"03/31/2020","description":"Closed for land management."}]}`

**Comment by gisdevcc** [comment]
Added more information link to list.json: https://github.com/fpdcc/trailsyserver/commit/11c286e38ca813dcc05254f4249dd879c78d14d6

fpdcc.com list js change needed: https://github.com/fpdcc/trailsy-vis-staging/commit/093646b249b9d3bb97284299949b7586c688fa02#diff-16cedf80ade01c62bdd1ae931d0492330c0b62bf294c08c095ce2fab21a9298d

**Comment by versatilehuman** [comment]
@versatilehuman Needs to update js on fpdcc.com

**Comment by versatilehuman** [comment]
Looks good on production.
