### ISSUE TITLE
Alert history no longer exporting

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/trailsy#248]
.../alerts/history/:

![image](https://user-images.githubusercontent.com/7032169/68033732-4a15a980-fc8e-11e9-8a1a-691a0dc3791b.png)

.../alerts/history.csv doesn't load.

**Comment by versatilehuman** [comment]
@shua123 Believe you said this had to do with a deleted user?

**Comment by gisdevcc** [comment]
Fix for alert history: https://github.com/fpdcc/trailsyserver/commit/b56d96fc3e2eb428d8504fc7371100def00f3422

**Comment by versatilehuman** [comment]
Works on production.
