### ISSUE TITLE
Satellite view appears to be broken

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/trailsy#249]

**Comment by versatilehuman** [comment]
If not an easy fix, try #208?

**Comment by shua123** [comment]
I think that is using an old url for the service that no longer works. This should probably be switched to https://img.cookcountyil.gov/arcgis/rest/services/Cook2018/ImageServer

**Comment by gisdevcc** [comment]
Switching to new cook gis imagery link https://github.com/fpdcc/trailsy/commit/3dd14e6749e34266f7303d051930fa4e2ee2caf1
