### ISSUE TITLE
Integrate Accessible Picnic Groves

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/trailsy#251]
- [x] New Columns
- [x] Panel
- [x] Map Icon & Pop-Up

### picnicgroves
- accessible
  - boolean 
- parking_to_shelter
  - distance in feet
- shelter_to_bathroom 
  - distance in feet
- bathroom_type
  - indoor OR portable

### points_of_interest
- accessible_shelter
  - boolean  

Based on data update: https://github.com/fpdcc/webmap_data_updates/issues/212

For here? https://github.com/fpdcc/trailsyserver/blob/development/db/schema.rb

### Javascript

**Add after this: https://github.com/fpdcc/trailsy/blob/development/js/panelFunctions.js#L604**

```
// accessible_shelter = Accessible Picnic Shelter
        if (poi.properties.tags[':panel'].indexOf('accessible_shelter') > -1) {
          fpccAmenitiesString += "<div class='fpccAmenity'><svg class='icon icon-accessible-picnic-grove'><use xlink:href='icons/defs.svg#icon-accessible-picnic-grove'></use></svg><span class='fpccAmenityTitle'><a href='https://fpdcc.com/permits/picnics-event-permits/'>Accessible Picnic Shelter</a></span></div>"
        }
```

### SVG

In updated defs.svg https://github.com/fpdcc/trailsy/commit/761268a88f707854e8bc978e44aa93a31946e6cf

### CSS
In updated newguts.css https://github.com/fpdcc/trailsy/commit/0b8cf1c4339d2dfabc41db55864b6460bd2d3519

## Map Icon & Popup

Building picnic groves on map: 
https://github.com/fpdcc/trailsy/blob/development/js/picnicgroveFeature.js

#### Icon
In **picnicgroves** table:
if **accessible = 1** --> use **icon-accessible-picnic-grove svg** on map

#### Popup
In **picnicgroves** table:
if **accessible = 1** --> Add these after `<div class="picnicgrove-capacity">Capacity: [picnicgroves --> capacity]</div>:`

```
<div class="picnicgrove-accessible-dates">Accessible May 1 to October 31.</div>
<div class="picnicgrove-accessible-parking">Distance to parking: [picnicgroves --> parking_to_shelter] ft</div>
<div class="picnicgrove-accessible-bathroom">Distance to accessible [picnicgroves --> bathroom_type] bathroom: [picnicgroves --> shelter_to_bathroom] ft</div>
```
Use conditionals for [parking_to_shelter], [bathroom_type] & [shelter_to_bathroom] in case those are empty for some reason.

### CSS

In updated newguts.css https://github.com/fpdcc/trailsy/commit/0b8cf1c4339d2dfabc41db55864b6460bd2d3519

## Result
![image](https://user-images.githubusercontent.com/7032169/73986958-95ca9580-4904-11ea-925e-fb73a393fda3.png)

**Comment by versatilehuman** [comment]
## New Columns

### picnicgroves
- accessible
  - boolean 
- parking_to_shelter
  - distance in feet
- shelter_to_bathroom 
  - distance in feet
- bathroom_type
  - indoor OR portable

### points_of_interest
- accessible_shelter
  - boolean

**Comment by versatilehuman** [comment]
## Panel

### Javascript

**Add after this: https://github.com/fpdcc/trailsy/blob/development/js/panelFunctions.js#L604**

```
// accessible_shelter = Accessible Picnic Shelter
        if (poi.properties.tags[':panel'].indexOf('accessible_shelter') > -1) {
          fpccAmenitiesString += "<div class='fpccAmenity'><svg class='icon icon-accessible-picnic-grove'><use xlink:href='icons/defs.svg#icon-accessible-picnic-grove'></use></svg><span class='fpccAmenityTitle'>Accessible Picnic Shelter</span></div>"
        }
```

### SVG

**Add to https://github.com/fpdcc/trailsy/blob/development/icons/defs.svg**

```
<symbol id="icon-accessible-picnic-grove" viewBox="0 0 32 32">
		<title>Accessible Picnic Grove with Shelter</title>
		<path fill="rgb(12, 81, 163)" class="path1" d="M32,27.9c0,0.6-0.2,1.1-0.3,1.5c-0.2,0.5-0.5,0.9-0.8,1.4c-0.8,0.8-1.7,1.2-2.7,1.2H4c-1.1,0-2-0.5-2.7-1.2
	C0.5,30,0,29.1,0,27.9v-24c0-1.1,0.5-2.1,1.2-2.9C2,0.5,2.9,0,4,0H28c1.1,0,2,0.5,2.7,1.2c0.5,0.5,0.8,0.8,0.9,1.4
	C31.8,3,32,3.6,32,4.1V27.9z"/>
<path fill="rgb(255, 255, 255)" class="path2" d="M17.8,19.1c0.2-0.8,0.5-1.4,1.1-2c0.2-0.2,0.5-0.5,0.6-0.6c0,0,0.2,0,0.2-0.2L19.5,15h-0.2
	c-0.9,0.5-1.8,1.4-2.3,2.4c-0.3,0.6-0.5,1.1-0.5,1.7c0,0.2,0,0.8,0,1.1c0,0,0,0.2,0,0.3c0.3,1.8,1.7,3.4,3.4,4
	c0.5,0.2,0.8,0.2,1.2,0.3c0.2,0,0.8,0,0.9,0c0.5,0,0.8-0.2,1.1-0.3c1.2-0.5,2.1-1.4,2.7-2.4v-0.2L25.4,21C25.1,20.5,25,20,25,20
	s0,0,0,0.2c0,0.3-0.2,0.6-0.2,0.8c-0.3,0.8-0.9,1.5-1.7,2c-0.3,0.2-0.5,0.2-0.8,0.3c-1.1,0.3-2.1,0.2-2.9-0.5
	c-0.2-0.2-0.3-0.3-0.6-0.5c-0.6-0.6-0.9-1.2-1.1-2c0-0.3,0-0.3,0-0.8C17.8,19.3,17.8,19.3,17.8,19.1z"/>
<path fill="rgb(255, 255, 255)" class="path3" d="M29.4,21c0,0-0.3,0.2-0.8,0.3c-0.5,0.2-0.8,0.3-0.8,0.3s-0.5-1.1-1.1-2.3c-0.6-1.2-0.9-2.3-1.1-2.3
	c0,0-3.2,0-4.1,0h-0.5v-0.3c0-0.2,0-0.5,0-0.5v-0.2h1.7h1.7v-0.6v-0.8h-1.7h-1.7c0,0-0.2-2.6-0.2-2.7c0.2,0,0.5-0.2,0.6-0.3
	c0.3-0.3,0.6-0.6,0.6-1.1c0-0.3,0-0.5-0.2-0.6c-0.2-0.3-0.5-0.6-0.9-0.8c-0.2,0-0.3,0-0.5,0c-0.6,0.2-1.1,0.8-1.1,1.4
	c0,0.2,0,0.3,0.2,0.6v0.2l0.3,3.5c0.2,2,0.3,3.5,0.3,3.5s1.1,0,2.4,0h2.4l1.1,2.4c0.6,1.4,1.1,2.4,1.1,2.4l2.6-1.1
	C29.9,22,29.4,21.1,29.4,21z"/>
<path fill="rgb(255, 255, 255)" class="path4" d="M7.3,13.2l20.9-7.9C28,4.6,27.9,4.3,27.7,4c-0.2-0.3-0.2-0.5-0.2-0.6L1.7,13.2c0.2,0.5,0.3,0.9,0.5,1.2
	c0.2,0.3,0.2,0.5,0.2,0.6l2.9-1.1v13.4h21v-1.8H7.3V13.2z"/>
	</symbol>
```

**Update to replace fill with `#0A315C`:**

```
...
<symbol id="icon-aquatic-center" viewBox="0 0 1024 1024">
		<title>Aquatic Center</title>
		<path fill="#0A315C" class="path1" 
...
<symbol id="icon-boat-launch" viewBox="0 0 1024 1024">
		<title>Boat Launch</title>
		<path fill="#0A315C" class="path1" 
...
<symbol id="icon-boat-rental" viewBox="0 0 1024 1024">
		<title>Boat Rental</title>
		<path fill="#0A315C" class="path1" 
...
<symbol id="icon-canoe-landing" viewBox="0 0 1024 1024">
		<title>Canoe Landing</title>
		<path fill="#0A315C" class="path1" 
...
```

**Update to replace fill with `#585747`:**

```
...
<symbol id="icon-bathroom-building-ada" viewBox="0 0 32 32">
	<title>Accessible Bathroom Building</title>
	<path fill="#585747" class="path1"
...
<symbol id="icon-bathroom-portable-ada" viewBox="0 0 32 32">
	<title>Accessible Portable Bathroom</title>
	<path fill="rgb(12, 81, 163)" class="path1"
...
```

### CSS
**Update fill in this line: https://github.com/fpdcc/trailsy/blob/development/styles/css/newguts.css#L380**

`#icon-aquatic-center .path1,#icon-canoe-landing .path1,#icon-boat-launch .path1,#icon-waterbody .path1,#icon-facebook .path1{fill:#0A315C}`

**Remove ADA icons from this line: https://github.com/fpdcc/trailsy/blob/development/styles/css/newguts.css#L378**

`#icon-bathroom-building-ada .path1` & `#icon-bathroom-portable-ada .path1`

**Add this line:**

`#icon-bathroom-building-ada .path1,#icon-bathroom-portable-ada .path1,#icon-accessible-picnic-grove .path1{fill:#0c51a3}`

**Comment by versatilehuman** [comment]
## Picnic Groves on map:

Building picnic groves on map: 
https://github.com/fpdcc/trailsy/blob/development/js/picnicgroveFeature.js

### JavaScript
#### Icon
In **picnicgroves** table:
if **accessible = 1** --> use **icon-accessible-picnic-grove svg** on map

#### Popup
In **picnicgroves** table:
if **accessible = 1** --> Add these after `<div class="picnicgrove-capacity">Capacity: [capacity]</div>:`

```
<div class="picnicgrove-accessible-dates">Accessible May 1 to October 31.</div>
<div class="picnicgrove-accessible-parking">Distance to parking: [parking_to_shelter] ft</div>
<div class="picnicgrove-accessible-bathroom">Distance to accessible [bathroom_type] bathroom: [shelter_to_bathroom] ft</div>
```
Use conditionals for [parking_to_shelter], [bathroom_type] & [shelter_to_bathroom] in case those are empty for some reason.

### CSS

**Add after here: https://github.com/fpdcc/trailsy/blob/development/styles/css/newguts.css#L340**

```
.picnicgrove-accessible-dates, .picnicgrove-accessible-parking, .picnicgrove-accessible-bathroom {border-top: 1px dotted #CCC;padding: .5em 0; margin: 0 .75em}
```

Update: https://github.com/fpdcc/trailsy/blob/development/styles/css/newguts.css#L346 to:
`.leaflet-popup-content-wrapper .leaflet-popup-content .activity-popup,.leaflet-popup-content-wrapper .leaflet-popup-content .picnicgrove-popup{border:0;padding:.5em .75em;font-weight:bold}`

**Comment by gisdevcc** [comment]
@versatilehuman When there is an accessible shelter do you still want the "Picnic Grove (with shelter)" in the panel too, or just the accessible one?
![image](https://user-images.githubusercontent.com/86254582/124157202-1fc95000-da5e-11eb-8223-dc9de98c2044.png)

**Comment by versatilehuman** [comment]
@gisdevcc pulling from the points_of_interest boolean columns I didn't think we'd be able to differentiate between locations where (a) all of the groves with shelters are accessible, or (b) only some of the groves with shelters are accessible. If we tapped into the activities table we could, but I think there is a potential benefit in having both--saying there is at least one picnic grove with a shelter and at least one shelter is accessible. Because the accessibility is at the shelter level and not necessarily at the grove level. Visitors can get more specific on the map itself.

**Comment by gisdevcc** [comment]
db updates: https://github.com/fpdcc/trailsyserver/commit/93fb8c3cd8f8137698ed130b2b145c24a3299b06

**Comment by gisdevcc** [comment]
On staging for review

**Comment by versatilehuman** [comment]
Looks good.
