### ISSUE TITLE
manifest.json 404

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/trailsy#252]
![image](https://user-images.githubusercontent.com/7032169/73862883-ce834580-4804-11ea-9735-f372f1b5ee50.png)

**Comment by versatilehuman** [comment]
Not sure what the issue is... I see it in the repository.

**Comment by gisdevcc** [comment]
This is a server configuration issue. It is fixed for staging. I'll need to fix it for production when we move the other changes to production.

**Comment by versatilehuman** [comment]
Looks good on production.
