### ISSUE TITLE
Old feedback links in (ghost?) About section

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/trailsy#253]
Someone reported seeing this here when viewing page source in their browser.

Looks like here:
https://github.com/fpdcc/trailsy/blob/development/index.html#L83

And then the BuildFeedbackLink is overwriting it?
https://github.com/fpdcc/trailsy/blob/development/js/panelFunctions.js#L81

![image](https://user-images.githubusercontent.com/7032169/73874379-08f6dd80-4819-11ea-9803-c74168099537.png)

**Comment by gisdevcc** [comment]
Fixed with https://github.com/fpdcc/trailsy/commit/f1706bf90606285532b9a1222b7ded345382896b

**Comment by versatilehuman** [comment]
Looks good on production
