### ISSUE TITLE
Button adjustments

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/trailsy#254]
## POI buttons

Around here:
https://github.com/fpdcc/trailsy/blob/development/js/panelFunctions.js#L446

- [x] Add a container (`.fpccButtonContainer`) around the directions button (and new button)
- [x] Add a conditional to build a button for the location's web page if it exists (poi_desc --> web_link column) and have it display: "Location Webpage".
   - This button should have the additional `secondary` class and a new ID (noted below) if needed.
   - Do we need a separate analytics type for this?

Resulting in this:
```
<div class="fpccButtonContainer">

<a href="[dynamic directions link]" target="_blank" id="entranceDirections" class="fpccButton fpccDirections" data-analyticstype="Directions" data-analyticsdescription="[points_of_interest --> name]">Directions</a>

<a href="[poi_desc --> web_link]" id="entranceWebsite" class="fpccButton secondary" data-analyticstype="?" data-analyticsdescription="[points_of_interest --> name]">Location Webpage</a>

</div>
```

![image](https://user-images.githubusercontent.com/7032169/74197089-519d0500-4c24-11ea-8daa-3df041f2df80.png)

### CSS

**CSS handled in updated newguts.css https://github.com/fpdcc/trailsy/commit/0b8cf1c4339d2dfabc41db55864b6460bd2d3519**

**Comment by versatilehuman** [comment]
## Trail Buttons

Around here:
https://github.com/fpdcc/trailsy/blob/development/js/panelFunctions.js#L893

- Remove label: `<span class="fpccLabel">PDF Trail Map:</span>`
- Adjust first button text to "PDF Map"
- Replace second button with a conditional to build a button for the trail's web page if it exists (trails_desc --> web_link column) and label "Trail Web Page".
   - This button should have the additional `secondary` class and a new ID (noted below) if needed.

Resulting in this:

```
<div class="fpccTrailMaps clearfix trailMaps">

<a class="fpccButton" id="pdfEnglish" href="http://fpdcc.com/downloads/maps/trails/english/FPCC-Salt-Creek-Trail-Map-9-16.pdf" target="_blank">PDF Map</a> 

<a class="fpccButton secondary" id="trailWebsite" href="https://fpdcc.com/places/trails/salt-creek-trail-system/" target="_blank">Trail Web Page</a>

</div>
```

![image](https://user-images.githubusercontent.com/7032169/74166597-75445900-4bec-11ea-92d6-3dedd448115a.png)

**Comment by versatilehuman** [comment]
@gisdevcc Can we flip the Trail Webpage and PDF Map buttons, to prevent this (all trails have a webpage, but not all trails have a PDF map):

![image](https://user-images.githubusercontent.com/7032169/125095000-5aa03900-e099-11eb-9e3e-f31cad9b2f24.png)

So the result we are looking for is this. Trail Webpage first, PDF Map second (with "secondary" class added):

```
<div class="fpccTrailMaps clearfix trailMaps">
<a class="fpccButton" id="trailWebsite" href="https://fpdcc.com/places/trails/salt-creek-trail-system/">Trail Webpage</a>
<a class="fpccButton secondary" id="pdfEnglish" href="https://fpdcc.com/downloads/maps/trails/english/FPCC-Salt-Creek-Trail-Map-9-16.pdf" target="_blank">PDF Map</a>
</div>
```
Resulting in:
![image](https://user-images.githubusercontent.com/7032169/125095481-d601ea80-e099-11eb-8524-a33c86775e70.png)

Or if no PDF:
![image](https://user-images.githubusercontent.com/7032169/125095568-ee720500-e099-11eb-8b9f-efdd03ed98e9.png)

**Comment by gisdevcc** [comment]
This is updated on staging
