### ISSUE TITLE
Add Search for Accessible Amenities

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/trailsy#261]
Add here (does it need to be added elsewhere?):
https://github.com/fpdcc/trailsy/blob/development/index.html#L123

`<option value="accessible">Accessible Amenities</option>`

Would return results for **accessible = 1** in the **points_of_interest** table.

Could then combine with other searches to find an accessible picnic shelter, canoe landing, etc.

Column already exists, populating it here: https://github.com/fpdcc/webmap_data_updates/issues/241

**Comment by versatilehuman** [comment]
@gisdevcc Is there an easy way to omit trails from any searches that use ?search=accessible

We aren't to a place where we can call trails or trailheads accessible, so this isn't great. Eventually we'd want to include them and would probably mark them accessible at the trailhead level.

![image](https://user-images.githubusercontent.com/7032169/124995223-a953c180-e00c-11eb-816e-9363620e530c.png)

**Comment by gisdevcc** [comment]
@versatilehuman From the list only or omit from the map too?

**Comment by versatilehuman** [comment]
@gisdevcc Let's keep on the map for now.

**Comment by gisdevcc** [comment]
Trail adjustment is up on staging.
