### ISSUE TITLE
Update basemap

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/trailsy#265]
Here: https://map.fpdcc.com/basemap_styles/fpdcc_style.yaml

![image](https://user-images.githubusercontent.com/7032169/106666381-22864e80-656d-11eb-8995-e94b1cfbb581.png)

With: https://github.com/fpdcc/webmap_data_updates/tree/master/basemap

Also need to document this process (https://github.com/fpdcc/trailsy/issues/257).

**Comment by gisdevcc** [comment]
This can be updated when I move the other items to production.
