### ISSUE TITLE
Updated Zipline language in panel & search

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/trailsy#267]
Changing title to "Zipline & Adventure Park"

## Panel

https://github.com/fpdcc/trailsy/blob/development/js/panelFunctions.js#L655

```
// zip_line = Zip Line
        if (poi.properties.tags[':panel'].indexOf('zip_line') > -1) {
          fpccAmenitiesString += "<div class='fpccAmenity'><svg class='icon icon-zip-line'><use xlink:href='icons/defs.svg#icon-zip-line'></use></svg><span class='fpccAmenityTitle'>Zipline & Adventure Park</span></div>"
        }
```

## Search

https://github.com/fpdcc/trailsy/blob/development/index.html#L150

`<option value="zip_line">Zipline & Adventure Park</option>`

**Comment by gisdevcc** [comment]
https://github.com/fpdcc/trailsy/commit/7724fc847f6355700a26e80cf8e30a9a482de87a
