### ISSUE TITLE
CSS update bugs

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/trailsy#269]
I mucked this up in CSS:

![image](https://user-images.githubusercontent.com/7032169/124314373-e9f89a00-db37-11eb-932f-11a717181354.png)

Missing arrow, POI flashes light green when clicked.

**Comment by gisdevcc** [comment]
I'm not sure what's going on here. Do you @versatilehuman ?

**Comment by versatilehuman** [comment]
@gisdevcc Yeah, need to fix along with some other CSS bugs and tweaks. I'll take care of it.

Arrow missing:
Revive this line:
![image](https://user-images.githubusercontent.com/7032169/124996742-16685680-e00f-11eb-9e72-2f6eba0fb3fd.png)

Line height on names:
![image](https://user-images.githubusercontent.com/7032169/124996606-d5704200-e00e-11eb-909b-4a5e9ba02a6c.png)

Vertical align on names:
![image](https://user-images.githubusercontent.com/7032169/124996965-7b23b100-e00f-11eb-8681-79e3f988c600.png)


Bump up font size on pop ups:

![image](https://user-images.githubusercontent.com/7032169/124997380-1f0d5c80-e010-11eb-8dbe-32182f325013.png)
![image](https://user-images.githubusercontent.com/7032169/124997554-70b5e700-e010-11eb-829c-bb7d8caa2f1b.png)
![image](https://user-images.githubusercontent.com/7032169/124997618-96db8700-e010-11eb-96ec-27ce01c15cbf.png)

**Comment by versatilehuman** [comment]
@gisdevcc These are done: https://github.com/fpdcc/trailsy/commit/6b0b5d8a2455cabe180833f47be0e37f9041fad4
