### ISSUE TITLE
Palos Single Track displaying as paved on the map

### ISSUE THREAD

**Issue by versatilehuman** [fpdcc/trailsy#270]
@gisdevcc Not sure what is going on. Panel is correct:

![image](https://user-images.githubusercontent.com/7032169/124995874-a2797e80-e00d-11eb-959d-36c0ae71ade8.png)

Here is production:

![image](https://user-images.githubusercontent.com/7032169/124995919-b329f480-e00d-11eb-8db8-c88a1eb5b2d3.png)

**Comment by versatilehuman** [comment]
@gisdevcc Another clue. They initially render correctly (dotted) but after clicking on any trail (or POI connected to the trail) in Palos Trail System it renders incorrectly (solid line) and stays that way even after you click elsewhere.

**Comment by gisdevcc** [comment]
This is fixed for now but will crop up again when I do dependency updates later.

**Comment by versatilehuman** [comment]
Works on production.
